### ISSUE TITLE
can't run after pip install

### ISSUE THREAD

**Issue by maliberty** [eskiyerli/revedaRelease#11]
I ran pip install but I get:
```
% reveda
Traceback (most recent call last):
  File "/home/mliberty/.local/bin/reveda", line 5, in <module>
    from reveda import main
  File "/home/mliberty/.local/lib/python3.10/site-packages/reveda.py", line 31, in <module>
    import revedaEditor.gui.revedaMain as rvm
  File "/home/mliberty/.local/lib/python3.10/site-packages/revedaEditor/gui/revedaMain.py", line 42, in <module>
    import revedaEditor.backend.importViews as imv
  File "/home/mliberty/.local/lib/python3.10/site-packages/revedaEditor/backend/importViews.py", line 32, in <module>
    import revedaEditor.gui.editorWindows as edw
  File "/home/mliberty/.local/lib/python3.10/site-packages/revedaEditor/gui/editorWindows.py", line 128, in <module>
    import revedaEditor.gui.helpBrowser as hlp
  File "/home/mliberty/.local/lib/python3.10/site-packages/revedaEditor/gui/helpBrowser.py", line 14, in <module>
    from PySide6.QtWebEngineWidgets import (
ImportError: libsmime3.so: cannot open shared object file: No such file or directory
```

Using Ubuntu 22 under WSL

**Comment by eskiyerli** [comment]
I have searched the internet for the likely cause this error. Considering that you are using Ubuntu, would you try this?:
sudo apt install libnss3

**Comment by eskiyerli** [comment]
You could also try to install the binary version for Windows from the releases page.

**Comment by maliberty** [comment]
That plus libxkbfile seems to work.
